name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
    - name: Install dependencies
      run: dotnet restore ARPL.sln
    - name: Build
      run: dotnet build ARPL.sln --configuration Release --no-restore
    - name: Pack
      run: dotnet pack arpl/Arpl.csproj --configuration Release --no-build --output ./nupkg
    - name: Push to NuGet
      run: dotnet nuget push "./nupkg/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
